import Head from 'next/head'
import Register from './register'

export default function Index() {
  return (
    <div>
      <Head>
        <title className="">Jeff</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className=" min-h-full flex justify-center items-center">
        <Register />
      </div>
    </div>
  )
}
